check: use dereferenced type when checking len
Reproduction of bug:

$ cat > t.ha <<'EOF'
use fmt;

export fn main() void = {
	let t: []int = [1, 2, 3];
	let t = t: *[*]int;
	fmt::println(len(t))!;
};
EOF
$ hare build t.ha
Assertion failed: len != SIZE_UNDEFINED (src/gen.c: gen_expr_measure: 2415)
Error: harec: exited with signal 6
hare build: build failed

This was caused by an incorrect check for a defined length, which is
fixed by this commit.

$ hare build t.ha
Error /var/tmp/t.ha:6:27: Cannot take length of array type with undefined length
Error: harec: exited with status 1
hare build: build failed

Signed-off-by: Sebastian <sebastian@sebsite.pw>